### PR TITLE
Update dependencies and other minor changes

### PR DESCRIPTION
**Pull request by KingDarBoja**
This PR should bring back coverall CI reports.

Also, provide a range for `gevent` dependency by allowing fetching latest pre-releases.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@Cito I see you have re-enabled coveralls, shall I close this PR?

**Comment by Cito** [comment]
@KingDarBoja Sorry, did not see you already created a PR for this. You made a few more changes which look reasonable, so we should merge it. Maybe just revert the change to tox.ini since I added coverage already there. I run it only for one Python version to make it faster since coveralls is only using one result anyway.

**Comment by KingDarBoja** [comment]
Based on your comment, this does mean we should do the same thing for every other **graphql-python** that makes use of coveralls to speed up the Travis CI, right?

**Comment by Cito** [comment]
> Based on your comment, this does mean we should do the same thing for every other **graphql-python** that makes use of coveralls to speed up the Travis CI, right?

Actually, I'm not really sure what's considered best practice here. But tox tests can be pretty slow when all of them run with coverage. I also noticed that branch coverage is sometimes lower with newer Python versions, since coverage does not cope with clever optimizations built into these versions. Sometimes there are also code parts that are only needed in certain Python versions, these would then decrease coverage in the other versions even though they are not necessary there. So coverage should be probably measured with one of the newer Python versions, but not the newest one. Finally, some projects have already switched to codecover instead of coveralls which looks newer and seems to have some advantages.

In graphql-core 3 I reached 100% coverage, but I needed to add many pragma hints and rules to help coverage ignore the mentioned optimizations. Here I measure coverage with all Python versions, and create an error if it is below 100% in any of these versions.

**Comment by KingDarBoja** [comment]
Thanks for the explanation @Cito ! It really helps a lot for someone to explain things like that instead of blindly implementing that feature because any other repository does.

Once again, I do really appreciate the feedback 💯

**Pull request merged**
