### PR TITLE
Add py.typed file to allow users to use the types this library provides

### PR DESCRIPTION
**Pull request by ckarnell**
I was generating type stubs for this library and noticed it already has some decent typing! This PR adds a py.typed file to the library, allowing consumers to use the types for type checking their own projects.

### CODE REVIEW

**Review by Cito — COMMENTED** [review]
I think you also need to add `package_data={"graphql": ["py.typed"]},` to setup.py.

**Comment by ckarnell** [comment]
Ah, thanks @Cito . Added!

**Comment by ckarnell** [comment]
@Cito I added the required change and now tests seem to be failing, but not the same ones. Their output is a little hard to read, is there any chance you can help me understand?

**Comment by Cito** [comment]
@ckarnell. Tanks for the change. I have restarted the failing tests and their are green now. Looks like this is caused by dict sort order which is random in Py 2.7 and 3.4 where the tests were failing. This needs to be fixed independently if it happens again.

**Review by Cito — APPROVED** [review]

**Comment by ckarnell** [comment]
@Cito Got it. Thank you!

**Pull request merged**
