### PR TITLE
Add test that pins down the order that middleware is executed in

### PR DESCRIPTION
**Pull request by dan98765**
Create dedicated test file for middleware (test_middleware.py) and add test that pins down the order that middleware is executed in.

This PR:

1. Moves existing middleware tests into new dedicated file test_middleware.py
2. Adds a test (`test_middleware_chain`) that asserts on the order middleware is executed in, as discussed in #155. It does not change that behavior. 

Info about pytest's `capsys` can be found here: https://docs.pytest.org/en/latest/capture.html

### CODE REVIEW

**Comment by dan98765** [comment]
I'm going to do this as 2 separate PRs. First https://github.com/graphql-python/graphql-core/pull/197 to give middleware its own separate test file. Then I'll revisit this branch so the diff is just focused on the new testing.

**Comment by syrusakbary** [comment]
Sounds good! Let me know once is ready to re-review :)

**Comment by dan98765** [comment]
Merged the latest master, the diff became much smaller. Also added type annotations so `tox -e mypy` passes. 

@syrusakbary this is ready for re-review.

**Comment by syrusakbary** [comment]
Looks good. Merging

**Pull request merged**
