### PR TITLE
Allow merging of types when one is an interface for the other

### PR DESCRIPTION
**Pull request by sdcooke**
The first issue I mentioned in https://github.com/graphql-python/graphql-core/issues/48 is fixed in the latest version (thanks!).

I think this fixes the second issue, which it turns out I couldn't easily work around it. I'm not 100% certain this is a valid thing to do so I won't be offended if you reject this pull request!

### CODE REVIEW

**Comment by syrusakbary** [comment]
Hi @sdcooke, can you find the related GraphQL-js commit for that (any commit from version `0.4.14` and ahead), I've checked at the latest code and differs from the `0.4.13` current code and your PR too.
https://github.com/graphql/graphql-js/blob/master/src/validation/rules/OverlappingFieldsCanBeMerged.js

Even knowing that your code is doing things in a perfect way, I think its a good practice to keep the code in sync with the js implementation. If is not in sync changes in code between repos are quite difficult to track. (and porting from one to another too)

**Comment by sdcooke** [comment]
Ah I didn't realise that this was being kept in sync with GraphQL-js - I'll take a look tomorrow to work out how GraphQL-js handles this situation and will see if I can make this PR match (assuming that it does handle it).

**Comment by sdcooke** [comment]
I've worked out that this issue was fixed in GraphQL-js for version 0.5.0 in this commit https://github.com/graphql/graphql-js/commit/c034de91acce10d5c06d03bd332c6ebd45e2213c which is a bit more complex that what I've done here. It refactors the overlapping checks. Are you planning on eventually getting to parity with 0.5.0 and higher? For now I can use my forked version - are you looking for more contributors to help push this forwards?

**Comment by syrusakbary** [comment]
I just opened an issue for start working in `v0.5.0` compatible with the Apr 2016 changes in the `GraphQL` spec.

https://github.com/graphql-python/graphql-core/issues/53

Any work there will be very welcome! (just comment saying with changes you will work on 😉 )

**Comment by syrusakbary** [comment]
I believe this is no longer necessary as the `master` branch now reflects all the improvements of `graphql-js` v0.5.0.

Closing the PR

**Pull request closed without merging**
