### PR TITLE
Travis uses tox

### PR DESCRIPTION
**Pull request by dan98765**
Travis runs various tox environments to do testing. 

In addition:

1.  Drop py33 support
2. Do not run flake8 or isort as part of tox; those are taken care of via pre-commit; 
    a. isort added in https://github.com/graphql-python/graphql-core/pull/187
    b. flake8 added in https://github.com/graphql-python/graphql-core/pull/191

### CODE REVIEW

**Comment by dan98765** [comment]
py27 and pypy are failing due to https://github.com/graphql-python/graphql-core/issues/189 - I think it makes sense to fix that as a separate branch then circle back to this one when it's resolved to prevent this branch getting even more enormous. 

*edit* fix is over at https://github.com/graphql-python/graphql-core/pull/190

**Comment by dan98765** [comment]
@syrusakbary I've resolved merge conflicts with latest master. What do you think of merging this in?  I think it makes the travis behavior easier to understand and also contributers who run `tox` will end up getting the same behavior as travis so no surprises. It'll also match graphene with https://github.com/graphql-python/graphene/pull/737

**Comment by syrusakbary** [comment]
I'm working on adding static type checking. Since it will probably merge conflicts between this two branches (as this is also formatting some code), I will wait to merge.

https://github.com/graphql-python/graphql-core/pull/193

**Comment by syrusakbary** [comment]
If you want to rebase from master I will happily review this PR again :)

**Comment by dan98765** [comment]
@syrusakbary OK will do! I still think having pre-commit (which runs flake8 and other checks) run as part of travis will help maintain good code quality. I'll see about updating this one tonight.

**Comment by dan98765** [comment]
@syrusakbary this is ready for a review.

**Pull request merged**
