### PR TITLE
Use Promises in execute context

### PR DESCRIPTION
**Pull request by syrusakbary**
This PR improves the executor abstraction by using Promises.
At the same time, removes all the usage of the Middlewares as are no longer necessary.

The `Promise` implementation is based in [aplus](https://github.com/xogeny/aplus) with a lot of improvements and fixes like `Promise.all`, `promise_for_dict`, `promise.do_resolve`.

_The resolvers can now return a raw object or a promise._
## Executors

The following executors are available:
- `graphql.execution.executors.asyncio.AsyncioExecutor`: This executor executes the resolvers in the Python asyncio event loop.
- `graphql.execution.executors.asyncio.GeventExecutor`: This executor executes the resolvers in the Gevent event loop.
- `graphql.execution.executors.asyncio.ProcessExecutor`: This executor executes each resolver as a process
- `graphql.execution.executors.asyncio.ThreadExecutor`: This executor executes each resolver in a Thread.
- `graphql.execution.executors.asyncio.SyncExecutor`: This executor executes each resolver synchronusly (default).
## Usage

You can specify the executor to use via the executor keyword argument in the `grapqhl.execution.execute` function.

``` python
from graphql.execution.execute import execute

execute(schema, ast, executor=SyncExecutor())
```

If no executor is specified, `SyncExecutor` will be used by default.

### CODE REVIEW

**Comment by Globegitter** [comment]
@syrusakbary that is great stuff! So if I use a library that returns a `Future` should I be able to simply wrap that in a promise? 

So what I am imagining is using the `SyncExecutor` but every resolve function that does some IO would return 'immediately' with a `Promise`. Inside the resolver we are using a request library (GRPC) that returns a `Future` for any IO calls. This `Future` I would then wrap in a `Promise`, which, via `.then()` will return the Promise with actual resolve result.

Is that something that should work with this implementation?

**Comment by jhgg** [comment]
Neat!

**Comment by jhgg** [comment]
Process and thread executor should be able to delegate to a pool (shared or individual pool per execution) of finite size. To prevent large queries from blowing the OS

**Comment by syrusakbary** [comment]
@Globegitter is not necessarily that, your resolver function could return a `Future` too and will work!
(But you need to specify the executor as `AsyncioExecutor`)

**Comment by syrusakbary** [comment]
But if you want to use `Promise`s it will work too (even with the `SyncExecutor`)

**Pull request merged**
